owtf/owtf

- README.md
added flag to wget which will overwrite older bootstrap.sh if present .
> fixed #359

- profiles/resources/default.cfg
The committed change adds us an extra feature which allows us to search for CVE details for any product+vendor.
Using passive google search.
> New vulnerability search resources

- install/install.py
Add support in install/install.py for automatically distro detection
> Remove user input for distro detection

- install/install.py
- install/proxy_CA.sh
Just saw these typos while I was installing OWTF and figured I'd correct them because I have OCD
> Fixed minor typos

- install/db_config_setup.sh
** Creates db.cfg file and skips db_run.sh execution
> Add parameter --cfg-only to skip postgres setup

- install/distro-independent.cfg
- install/update_convert_cms_explorer_dicts.sh
* move the download (wget) to distro-independent.cfg as it can make use
* of the wget_wrapper
> Download cms explorer sources outside the script

- profiles/resources/default.cfg
Issue #399 partial fix for Ftp, Smtp, Vnc, Emc, MsSql, MsRpc, HttpRpc,
Smb, Snmp Probe Methods
> Replace msfcli with msfconsole

- framework/config/config.py
- framework/config/framework_config.cfg
- framework/utils.py
I hardcoded ~/.owtf. Where should this default path be added? default.cfg is not a good idea because users can modify it and we want "~/.owtf" to be the failure solution for bad config.
> Check access rights for OUTPUT_PATH

- install/arch/PKGBUILD
- install/arch/default.cfg.patch
what do you suggest regarding sha1sums? should exist any checks? also, I mention that this change can be merged only after merging #486(mandatory) and #488  (optional).
> OWTF AUR package

- install/aptitude-wrapper.sh
- install/kali/install.sh
* used in install/kali/install.sh
* check available disk space before installing packages using apt-get
> Add aptitude wrapper support for kali script

- install/distro-independent.cfg
- install/install.py
- install/space_checker_utils.py
* add wget wrapper to check if the download can proceed
* install tools only after enough space is available
> Add available space checking mechanism

- plugins/web/external/Testing_for_Command_Injection@OWTF-DV-013.py
- profiles/resources/default.cfg
Add External Command Injection Link
> Fix issue #412

- install/distro-independent.cfg
> wget retires limit

- install/install.py
This commit pushes distro independent stuff up in order. partial resolution to #534
> moving distro independent stuff above distro specific installs

- install/install.py
@delta24 The issue can now be closed. Now it is checking for empty directory and if found downloading again. I have tested it, working fine.
> Fixed empty folder issue during installation #544

- tests/test_cases/resources/www/robots/robots.txt
> Revert "robots.txt spelling mistakes corrected"

- framework/interface/templates/target_manager.html
@7a  @delta24 Please Review. Fixes #453
Screenshot attached with PR.
> filter by severity feature added

- framework/http/proxy/plugnhack/client_message.py
- framework/interface/api_handlers.py
- framework/interface/cli.py
@delta24 @DePierre I have corrected some import issues, please review.
> fixed import errors

- framework/core.py
- framework/db/plugin_manager.py
- framework/plugin/worker_manager.py
> Proper Fixes for issue #556

- framework/interface/templates/manager_interface.html
- framework/plugin/worker_manager.py
- includes/js/moment.js
@delta24 @7a @DePierre Please review. Fixes #419 
PFA screenshot.
> Display start time on the worker summary screen. Fixes #419

- scripts/run_arachni.sh
Corrected the arachni command which it display on the terminal
Not related to any issue
Helps user to see the correct command
@delta24 
Running the arachni plugin and see the terminal for output
Before
After
> Corrected arachni command to display

- framework/db/poutput_manager.py
- framework/interface/api_handlers.py
- framework/interface/templates/manager_interface.html
- framework/interface/ui_handlers.py
- framework/interface/urls.py
@delta24  @7a @DePierre Please Review. Fixes #373
As Discussed, I created Progress Bar on target page. I also added which worker is working on which plugin as suggested by @delta24.  
PFA screenshots.
> Progress Bar for Scan created on worker page. Fixes #373

- framework/db/target_manager.py
Fixes use of uninitialised variable in UpdateTarget function of target_manager.py
@delta24
> Fixes syntax error in UpdateTarget function of target_manager.py

- framework/interface/templates/target_manager.html
Added functionality to allow the removal/deletion of all marked targets. This also included making the `toggleAll()` function only affect visible rows (so filtering works as expected), and check-boxes remain checked after changing pages on the table.
Added button to remove all selected targets from current session.
Added button to delete all selected targets.
Successes and failures are tracked, individual reporting is possible but not implemented.
TargetTable now keeps track of checked inputs between pagination.
Using the 'select all' checkbox will only toggle visible inputs.
Made the delete/remove target functions more flexible, functionality unchanged.
https://github.com/owtf/owtf/issues/429
This change makes it faster to remove/delete multiple targets. They don't need to be operated on …
> Added bulk target operations: remove/delete

- framework/db/session_manager.py
- framework/interface/templates/target_manager.html
This PR truncates the length of session names to 50 characters.
Ref : #635 
The SessionModal breaks when really long session names were given as input.
Issue : #635 
@delta24 
Manually tested on a browser.
> Truncated long session names

- scripts/db_run.sh
- scripts/db_setup.sh
This PR fixes issue #662 . db_setup.sh was modified to handle the service controllers in a better way.
Issue #662 
@delta24 @DePierre @7a 
It was manually tested by removing `/usr/sbin/service` and `/bin/systemctl` from Kali Linux. I set debug values and tested if the fix was right.
> Better handling of service controllers

- owtf.py
Reverts owtf/owtf#659, The changes breaks and causes #375 issue
> Revert "set plugin group to web if not specified, fixes #390"

- framework/config/config.py
- framework/core.py
- framework/db/config_manager.py
- framework/db/plugin_manager.py
- framework/db/resource_manager.py
- framework/dependency_management/component_initialiser.py
- owtf.py
This will fix -m option of OWTF, enable user to use custom config files.
This PR change the initialization sequence of the OTWF, which enable resource, mapping to initialize after the argument parsing. 
#367 
Fixes broken -m option.
@delta24 @tunnelshade @DePierre @7a
touch /tmp/dummy
./owtf.py -m "g:/tmp/dummy,w:/tmp/dummy,n:/tmp/dummy,r:/tmp/dummy"
> Reorder the initialisation sequence, Fixes #367

- framework/db/plugin_manager.py
Reverts owtf/owtf#682. Issue described by @DarKnight-- is legit, needs to revert this asap.
> Revert "Addded plugin name to code converter function Fixes #650"

- AUTHORS
Updated information of @sachinkamath (me) .
> Update information in AUTHORS

- framework/interface/templates/target.html
changed checkbox to radio for mapping in target report filter
Mapping only shows one mapping, hence radio buttons are suited for this filter
#679 
@delta24 
…#679
> changed checkbox to radio for mapping in target report filter, Fixes #679

- framework/db/target_manager.py
- framework/interface/api_handlers.py
- framework/interface/templates/base.html
- framework/interface/templates/home.html
- framework/interface/urls.py
- includes/css/stylesheet.css
- includes/js/bundle.js
- includes/src/Home/Chart.js
- includes/src/Home/Home.js
- includes/src/constants.js
- includes/src/main.js
- package.json
This new feature creates a pie chart at home page that represents the previous target scans analytics. Also this is mobile responsive.
Each target has its severity value. To give a general overview of previous target scans, this feature creates a pie chart at home page using reactJS and [react-chartjs](https://github.com/jhudson8/react-chartjs). This feature will help the tester to overview his/her scans.
@delta24 @7a @anantshri @tunnelshade 
This feature is tested on Google chrome and mozilla firefox
> [webui] Severity Pie Chart Created

- framework/dependency_management/component_initialiser.py
- framework/dependency_management/dependency_resolver.py
- framework/selenium/selenium_handler.py
added the missing components
#696 
This change will help to fix aux plugins
@delta24 @DePierre 
tested 
`print(ServiceLocator.already_registered("selenium_handler"))`
`print(ServiceLocator.already_registered("smb"))`
`print(ServiceLocator.already_registered("interactive_shell"))`
and all of them print `True`
> Fixes #696

- install/distro-independent.cfg
- install/install.py
- install/setup_react.sh
- package.json
React setup instructions added to installation script.
@delta24 @anantshri @tunnelshade @7a 
This is tested on ubuntu.
> [webui] React setup script

- framework/error_handler.py
- framework/http/proxy/gen_cert.py
- framework/http/proxy/proxy.py
- framework/interface/api_handlers.py
- framework/interface/templates/target_manager.html
- framework/lib/filelock.py
- framework/lib/owtf_process.py
- framework/plugin/plugin_handler.py
@delta24 @7a @tunnelshade @anantshri
> [merge] Merging develop into ui_improvements

- gulpfile.js
- install/setup_react.sh
- package.json
- webpack.config.js
This PR adds JavaScript compression plugin to webpack and creates gulp development environment.
* $ gulp - This will run gulp which will listen to the changes in includes/src folder and rebuild the react bundle
@delta24 @7a @anantshri @tunnelshade
> [webui] Javascript compression plugin added to webpack and gulpfile created for development

- framework/interface/templates/target.html
- includes/css/stylesheet.css
Features - 
* Side Bar filter created which visible as user scrolls down.
* BreadCrumbs
* Return to Top button
* Mobile responsive
@delta24 @anantshri @7a @tunnelshade
> Report enhancements

- framework/interface/templates/config_manager.html
- framework/interface/templates/help.html
- framework/interface/templates/manager_interface.html
- framework/interface/templates/pnh/plugnhack.html
- framework/interface/templates/target_manager.html
- framework/interface/templates/worklist_manager.html
- framework/interface/templates/zest_console.html
- includes/src/Dashboard/Dashboard.js
- includes/src/Home/Home.js
- includes/src/Transactions/Transactions.js
@delta24 @7a @anantshri @tunnelshade
> [webui] BreadCrumbs created everywhere

- framework/interface/templates/base.html
- framework/interface/templates/target_manager.html
Keyboard navigation 
Features:
* Submit target using shift+enter 
* Move across pages using shift + left key(previous page)
Keyboard navigation can reduce mouse movements 
@delta24 @7a @tunnelshade @anantshri
> Keyboard navigation

- install/owtf.pip
> Merging develop branch into ui_improvements

- plugins/web/passive/Spiders_Robots_and_Crawlers@OWTF-IG-001.py
Fixed the bug created during cleanup of the code.
Fixed the call of the GetResources in OWTF-IG-001.py, causing the OWTF to freeze.
#715 
Fixes the bug.
@delta24 
Tried the plugin on various http/https targets.
> [plugin] Fixed GetResources call in Spiders_Robots_and_Crawlers@OWTF-IG-001.py

- framework/interface/custom_handlers.py
- framework/interface/templates/manager_interface.html
- framework/interface/ui_handlers.py
- includes/css/stylesheet.css
Worker Logs added on worker page
@delta24 @7a
> [webui] Worker Logs added on worker page

- install/owtf.pip
> Merging develop to ui_improvements

- install/setup_react.sh
Previously react setup script was not working properly on all linux distros. This PR will fix this issue.
@delta24 @7a
> [webui] Bug fixes in automatic react stack setup

- framework/interface/templates/target.html
- framework/interface/templates/target_manager.html
Currently label shown on target manager and target panel are different in case user ranks any plugin.
The problem is in the label is selected on the target manager page. It overrides rank of target if user ranks any plugin even if owtf rank is higher on at least one plugin. 
I have changed the label to get decided on the basis of `max(max_user_rank, max_owtf_rank)`.
#727 
@delta24 
Changed the owtf_rank accessing database of one plugin higher than the user_rank.
The severity of `critical` is set by `owtf_rank`. (Updated the database table using terminal to test the changes.)
> [ui] Fixed buggy severity label on target manager page, Fixes #727

- framework/interface/templates/plugin_report.html
- framework/interface/templates/target.html
Target page changed to full width container
@delta24 @7a
> [webui] Target page changed to full width container

- install/distro-independent.cfg
- install/setup_react.sh
Error were coming when it is installed like "python owtf/install/install.py". This PR will solve this bug. 
@delta24 @7a
> [webui] Bug fixes in react installation

- framework/interface/templates/target.html
- framework/interface/templates/target_manager.html
- install/distro-independent.cfg
> Merging develop into ui_improvements

- framework/db/command_register.py
- framework/db/poutput_manager.py
- framework/plugin/plugin_handler.py
- framework/plugin/worker_manager.py
- framework/shell/blocking_shell.py
Added handling of SQLAlchemyError when error occurs in database transaction.
This PR will fix the OWTF when it hangs in case a target is deleted under scan.
#675 
@delta24 @DePierre @7a 
Run the plugins against any target and delete the target when plugin is scanning. When the plugin finishes it raises error and the process exits successfully.
…when target is deleted, Fixes #675
> [Misc] Added exception handling for db commits to ensure smooth exit

- owtf.py
- webpack-dev.config.js
- webpack.config.js
Previously there was bug when owtf not starts from owtf repository.
@delta24 @7a
> [webui] Fixes build error on owtf startup

- framework/db/command_register.py
- framework/db/poutput_manager.py
- framework/db/transaction_manager.py
- framework/plugin/plugin_handler.py
- framework/plugin/worker_manager.py
- framework/shell/blocking_shell.py
> Revert "Merging develop into ui_improvements"

- framework/interface/templates/manager_interface.html
1) Due to the issue mentioned in #758 , UI was giving errors. Hence 1st commit will solve this issue.
2) Performance improvement: Unnecessary poll to fetch full log to calculate lines.
@delta24 @7a @anantshri
> Worker log panel bugs

- install/owtf.pip
Tornado is marked as insecure, update to latest minor version
> Update tornado to latest (4.4.2)

- install/kali/install.sh
Added o-saft to kali's installation script
#772 
This will install o-saft tool.
@delta24 @7a 
Installed on Kali.
> Added o-saft to installation script, Fixes #772

- framework/interface/templates/manager_interface.html
- includes/src/Dashboard/WorkerPanel.js
Fixes the worker logs bug and adds button to display log.
#758 #769 
@delta24 @DarKnight24 @7a
> [worker] Fixes the worker logs bug and adds button to display logs

- framework/interface/templates/manager_interface.html
> [worker] Adds option to hide logs

- install/install.py
- owtf.py
The OWTF will exit if executed from its directory
Added a check confirming the OWTF is not executed from its directory.
#766  #746 
@delta24 @DarKnight24 @7a 
Tested it by running it from different directories.
> Fixes #766. OWTF will never run within its own directory.

- install/db_config_setup.sh
- scripts/db_run.sh
- scripts/db_setup.sh
Fixed various grep and sed errors in `db_setup.sh` and `db_run.sh`.
Removed forced administrative privilege from database scripts to fix `.owtf` folder creations.
Changed various grep and sed command to get correct IP of postgresql servers.
#767 
@delta24 @7a
> Fixed database related scripts

- includes/src/Dashboard/Chart.js
- includes/src/Dashboard/Dashboard.js
- includes/src/Dashboard/GitHubReport.js
- includes/src/Dashboard/Panel.js
- includes/src/Dashboard/WorkerPanel.js
- includes/src/Home/Home.js
- includes/src/Readme.md
- includes/src/Report/Accordian.js
- includes/src/Report/Accordians.js
- includes/src/Report/Collapse.js
- includes/src/Report/Header.js
- includes/src/Report/RankButtons.js
- includes/src/Report/Report.js
- includes/src/Report/SideFilters.js
- includes/src/Report/Table.js
- includes/src/Report/Toolbar.js
- includes/src/Transactions/Footer.js
- includes/src/Transactions/Header.js
- includes/src/Transactions/Targetlist.js
- includes/src/Transactions/TransactionHeader.js
- includes/src/Transactions/TransactionTable.js
- includes/src/Transactions/Transactions.js
PR submits the functional documentation for React Code written(New UI)
@delta24 @7a @DarKnight24
> React Documentation

- install/owtf.pip
- scripts/db_run.sh
- scripts/db_setup.sh
> Corrected if condition in db_run script

- install/debian/install.sh
Fixes install script as discussed in #809 
#809
@delta24
> Fixes error in install script

- includes/src/Report/Accordian.jsx
- includes/src/Report/Accordians.jsx
- includes/src/Report/Header.jsx
* Removes the loader image in fail response too.
* Updates the overall rank on Ranking plugins
@delta24
> Bug fixes in ui_improvements

- .travis.yml
- install/debian/install.sh
> Revert "Added sudo access and corrected update command"

- framework/utils.py
Updated the git version checker function to run command from owtf directory.
#830 
@viyatb 
Run the owtf
> Fixed git version checker, Fixes #830

- install/install.py
This will ensure install script will not break if environment variable are not set due to any reason
This bug was introduced during virtualenv setup PR review. I have added missing error handling.
#836 
@viyatb 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owtf/owtf/837)
> Added exceptional handling in virtalenv setup, Fixed #836

- scripts/run_nikto.sh
Update ssl switch routine to correctly handle ssl connection establishment check
add different routine check on openssl s_client -connect output to correctly identify a valid ssl connection
**https://github.com/owtf/owtf/issues/847**
previous routine checked only for the number of lines in the output of the openssl s_client -connect command to see if it was greater than 15. This check is not working anymore nowadays, since a failed connection output can be greater than 15 lines. With the proposed change, the code looks for the word "ESTABLISHED" in the ouput of the previous command plus the switch -brief, to check for a correctly established ssl connection.
@viyatb
Tested on kali distribution with local modification of the run_nikto.sh script.
Before the change, the check on a target on …
> Fix SSL check in nikto

- .travis.yml
Add `master` branch to be built by Travis.
> [travis] Let travis CI build the master branch

- scripts/ssl/reporter.py
- scripts/ssl/template.py
Cleaned up the reporter script and separated the HTML to be in `template.py`.
> [ssllabs] Fix reporter build and refactor template

- .gitignore
Add `yarn.lock` files for git to ignore.
> Ignore Yarn lock files

- owtf/scripts/setup_ui.sh
This flag was introduced so that bundled assets could be shipped with a release. This PR turns off that flag in the development branch.
> [install] Remove the OWTF_DEV flag for the time being

- scripts/install.sh
- Refactor check_sudo function to use $EUID to check for root user.
- Refactor db_setup function
- update logic to check if postgres service is running or not
- fix db_setup logic.
#927 
@viyatb @7a
> Refactor installation script.

- docker-compose.dev.yml
owtf-cli renamed to owtf. Updated here so that docker-compose works properly.
> owtf-cli renamed to owtf. Updated here so that docker-compose works properly.

- Makefile
- docker-compose.dev.yml
- docker-compose.yml
- scripts/install.sh
- fix ports in `docker-compose.yml`
- fix docker environment check in install script.
@viyatb
> fix(docker-compose): fix docker-compose ports and install script

- .gitignore
- add `owtf_review` to gitignore
@viyatb
> [gitignore]: refactor gitignore

- owtf/utils/formatters.py
- Fix console logging formatting to support python 3
- Fixes #948 
@viyatb
> fix(console-logging): fix python3 console logging formatting.

- owtf/core.py
- owtf/db/database.py
- owtf/http/transaction.py
- owtf/lib/cli_options.py
- owtf/managers/target.py
- owtf/managers/worker.py
- owtf/managers/worklist.py
- owtf/plugin/plugin_handler.py
- owtf/plugin/plugin_params.py
- owtf/plugins/auxiliary/dos/Direct_DoS_Launcher@OWTF-ADoS-001.py
- owtf/plugins/auxiliary/exploit/Exploit_Launcher@OWTF-AExP-001.py
- owtf/plugins/auxiliary/selenium/Selenium_URL_Launcher@OWTF-ASEL-001.py
- owtf/plugins/auxiliary/smb/SMB_Handler@OWTF-SMB-001.py
The PR address the following issues:
* Convert argparse switches to be Pythonic
* Better parsing logic and string interpolation.
* Exit when just `--help` or `--help --nowebui` are provided.
* Remove unused CLI options.
> Argument parsing logic and code refactor

- requirements.txt
* update psycopg2 version to 2.7.4 to resolve glibc issues.
* rearranged according to alphabetical order
Fixes #959 
@viyatb
> requirements: update psycopg2 version to 2.7.4

- owtf/__init__.py
- owtf/core.py
- owtf/db/database.py
- owtf/filesrv/main.py
- owtf/lib/owtf_process.py
- owtf/utils/logger.py
- owtf now exits cleanly when no postgreSQL server is running.
- Fixes #953 
@viyatb
> fix(953): exit cleanly when no postgreSQL db server is running

- owtf/api/handlers/config.py
- owtf/api/handlers/health.py
- owtf/api/handlers/plugin.py
- owtf/api/handlers/report.py
- owtf/api/handlers/session.py
- owtf/api/handlers/targets.py
- owtf/api/handlers/transactions.py
- owtf/api/handlers/work.py
This PR corrects docstrings for API methods. It is work above @viyatb PRs on new API.
@viyatb
> Corrects doc strings for new Rest APIs

- owtf/api/handlers/base.py
- owtf/api/handlers/config.py
- owtf/api/handlers/health.py
- owtf/api/handlers/plugin.py
- owtf/api/handlers/report.py
- owtf/api/handlers/session.py
- owtf/api/handlers/targets.py
- owtf/api/handlers/transactions.py
- owtf/api/handlers/work.py
- owtf/lib/exceptions.py
This PR provides a standardized set of sane default responses for API success, errors and failures. It also provides descriptive error messages on failures.
> Sane API responses and robust error handling

- owtf/api/handlers/base.py
- owtf/utils/app.py
- owtf/utils/error.py
- owtf/utils/logger.py
This PR provides an initial Sentry integration with the core framework and the Tornado applications.
Fixes https://github.com/owtf/owtf/issues/941
> Sentry integration with OWTF

- owtf/webapp/src/utils/request.js
Following adds support to handle data submission with POST/PATCH/PUT requests.
> Note: In order to use this, you will need to add appropriate header
``` 
headers: {
'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
}
```
@viyatb
> Handles application/x-www-form-urlencoded requests

- README.md
> Updates slack channel details.

- owtf/webapp/src/containers/HelpPage/index.js
Implemented the Help Page using Evergreen components.
@viyatb @saganshul
> Help page ported to evergreen UI

- owtf/webapp/package.json
evergreen-ui package added to package.json file
> package.json file updated

- owtf/webapp/src/components/ConfigurationTabsContent/index.js
- owtf/webapp/src/components/ConfigurationTabsNav/index.js
- owtf/webapp/src/containers/SettingsPage/index.js
Implemented the Settings Page using Evergreen components.
@viyatb @saganshul
> Settings Page ported to evergreen-ui

- owtf/webapp/src/containers/Transactions/TargetList.js
- owtf/webapp/src/containers/Transactions/TransactionHeader.js
- owtf/webapp/src/containers/Transactions/TransactionTable.js
- owtf/webapp/src/containers/Transactions/index.js
- owtf/webapp/src/containers/Transactions/saga.js
Implemented the Transaction Page using Evergreen components with minor bug fixes.
@viyatb @saganshul
> Implemented Transaction Page in evergreen-ui

- requirements/base.txt
I bumped the `pexpect` package to fix Python3.7 compatibility
#1018 
This PR fixes support for Python 3.7 and does not break compatibility with older versions. Tested this change with a Python2 venv as well.
@viyatb @7a 
Used both 3.7 and 2.7 virtualenvs and checked for errors as in screenshot above.
> Update requirements to fix python3.7 compatibility

- owtf/models/command.py
- owtf/models/plugin.py
Now the application can be installed manually
Importing plugin.py in command.py and test_group.py in plugin.py this fixes the issues related to the foreign key.
https://github.com/owtf/owtf/issues/1040
Previously users could not run OWTF through manual installation or through docker.
- [ X] Bug fix (non-breaking change which fixes an issue)
> Fix issue#1040

- owtf/scripts/setup_ui.sh
Fixes UI 
Running nvm install node was installing the latest version of node which very creating compatibility issues with the dependencies, and without WebUI.
Installing node v11.14.0 ensures that the node is compatible with all the packages.
Fixes issue https://github.com/owtf/owtf-docker/issues/36
> Fixes UI issues in owtf/owtf-docker
