install/db_config_setup.sh
Comparison error caused by starting the script with POSIX shell
=> Fix string comparison issue in db_config_setup.sh

install/owtf.pip
Default python-setuptools installs a deprecated version(0.6rc11)
=> Upgrade default python setuptools package to v18.1

install/distro-independent.cfg, install/install.py
this is a simple check added by a new if condition the whole block around kali linux should only run if distro is kali.
At later stage we should reduce this code also and may be create different distro profile or deprecate support for kali 1 as its not officially supported.
Fix #534
=> added check for kali linux block to run only if distro is kali

install/install.py
A change recently introduced check if the user has "sudo" permissions.
The check_sudo() function should also allow the installation to proceed if the user is root.
This Pull Requests checks  if the user has UID = 0 (equivalent to root) and proceed if it does have so, otherwise, print's the warning and exits cleanly.
=> Allow the install to proceed is user is root

install/kali/install.sh
Update the manifests from upstream kali repo in order to get the latest package package versions before performing intallation of packages required by OWTF.
This will address issues currently found when trying install of OWTF on a fresh Kali 2.0 VM downloaded from Offsec Website. Resolves #540
Signed-off-by: Doug Morato <dm@corp.io>
=> Perform "apt-get update" before install packages. Resolves #540

install/kali/install.sh
As metagoofil does not comes preinstalled with Kali 2.x, it is needed to be installed using its repository.
=> Added metagoofil in install.sh for Kali

.gitignore
As described in #562, the necessary files and directories for the following IDEs/ editors have been included in .gitignore :
- _**Pycharm IDE** - Jetbrains._
- `.idea/` directory and all its sub-contents in top level directory.
- _**PyDev IDE** - Eclipse._
- mainly `*.project` and `*.pydevproject` files, along with some other common eclipse generated files.
- _**YouCompleteMe** - Vim._
- `.ycm_extra_conf.py` in top level directory.
=> IDE specific auto-generated files now in .gitignore. Fixes #562

install/aptitude-wrapper.sh, install/db_config_setup.sh, install/debian/install.sh, install/kali/install.sh, install/samurai/install.sh
All the statements in shell scripts, which are meant to execute other shell scripts are prepended with "sh" in order to make sure that the script runs even if the permissions of script have the executable bit unset.
This workaround was enacted following the suggestion by @delta24 on #572 :
_"A possibly clean solution is to add either `sh` or `bash` in front of the script names everywhere. That way we don't play with permissions and source remains clean."_
=> Ensures execution of Debian and Samurai scripts. Fixes #572

install/db_config_setup.sh, install/kali/install.sh, install/proxy_CA.sh
Fixed problem with these scripts.I've tried to install owtf on my Kali Linux and the scripts were not creating the .owtf/proxy folder  and .owtf/db.cfg properly. That was  because the function get_config_value function (included in both scripts) was returning a bad value because the colours were making a bad path to the desired path.
And usage added to the /install/kali/install.sh script were teh OWTF project folder is required
=> Fixed return value of get_config_value() function

install/aptitude-wrapper.sh
The 'disk space' available was also colored cyan while colorizing the logs in the file **install/aptitude-wrapper.sh**, so it couldn't be compared with numerical data due to presence of stray ANSI codes. This PR intends to fix that error.
=> Fix for 'illegal number' problem of aptitude wrapper.sh

framework/http/proxy/cache_handler.py, framework/http/proxy/proxy.py
Replaces `headers.get_items()` to `headers.get_all()` in **framework/http/proxy/proxy.py** as directed in #582 to overcome the error.
The relevant screenshots:
* Before fixing:
* After fixing:
=> Fix Set-Cookie header handling in proxy. Fixes #582

framework/interface/templates/target_manager.html
Fixed Reflected XSS Vulnerability, which existed due to unsanitized session name.
Closes #613
=> Fixed Reflected XSS vulnerability

dictionaries/README, dictionaries/install_dicts.sh
Replaced mavitunasecurity.com with netsparker.com  as it was redirecting to netsparker.com. Rest of the url remains same.
=> Fixed mavitunasecurity.com redirection

install/install.py
- Installer class had only one instance, and no other usages.
- So to avoid wastage of memory by even making that instance, all the methods were converted to `classmethods` and now called directly in main. This improves performance.
- Apart from that there were minor PEP8 fixes for an overall cleanup of the script. Tested well, works fine.
=> Cleanup install script to reduce memory overhead.

framework/interface/templates/plugin_report.html
When viewing a target report for a plugin, if there is only one type of that plugin available. i.e. only active, or only bruteforce, then that tab will be open by default upon expanding the accordion
https://github.com/owtf/owtf/issues/429
Reduces number of clicks requred to view reports.
@delta24
Tested on a plugin with 1 type and also on plugins with multiple types.
=> Removed unnecessary click

plugins/web/active/Old_Backup_and_Unreferenced_Files@OWTF-CM-006.py
Instead of giving the command through a list (due to which commands don't run in order ), I am giving them one by one.
#642 
Dirbuster plugin will be working by now
@delta24 
I ran the dirbuster plugin and now commands ran in order and hence there was no such error like `Dirbuster.txt not found`
Screenshot shows that commands ran in order
=> Dirbuster plugin working fixes #642

framework/interface/templates/plugin_report.html
This PR is small optimization in reference to issue  #429.
Added a show less button at bottom, on clicking it Plugin gets collapse and auto scroll smoothly to plugin next to it. This will decrease a lot of vertical scrolling.
#429 
This will decrease a lot of vertical scrolling.
@delta24 @7a @DePierre 
This was tested on Firefox and Chromium and works as very well on both browsers.
=> Show less functionality added to optimize the click flow

framework/config/aux_testgroups.cfg, framework/config/framework_config.cfg, framework/config/net_testgroups.cfg, framework/config/web_testgroups.cfg, framework/db/plugin_manager.py
This pull request will fix -l option for auxiliary plugins. 
In this a test group file is added which contains information about all the auxiliary plugins. The corresponding function is modified in `plugin_manager.py` to load them in db.
This fixes issue #647 
This will fix the problem of not listing the available aux plugin in OWTF
@delta24 @DePierre 
To test the working of this pull request run `./owtf.py -l auxiliary`
=> added auxiliary plugin test group, this makes -l command functional

framework/db/command_register.py, framework/shell/blocking_shell.py
regarding force overwrite, the previous fix was limited only to CLI. This one is the proper fix which is applicable to GUI and CLI both 
IMO if the command failed or plugin output doen't exist then it should `return None` so that `CanRunCommand()` function can return True to run the given plugin.
#379 #639 
User will be able to rerun the plugin against same target from GUI as well
@delta24 @DePierre @7a @tunnelshade 
Just click on the rerun button and see the terminal, plugin should be running.
=> Fixes #639 and properly fixes #379

owtf.py
This PR sets the plugin group to web if not specified. This makes -t command functional.
Set the plugin_group to web if not specified.
#390 
@delta24 
./owtf.py -t passive
=> set plugin group to web if not specified, fixes #390

framework/interface/templates/manager_interface.html
This PR fixes the progress bar bugs referenced in #644
Fix of Bug-1 : To fix this bug, PR checks left_count == 0 and complete count == 0 and if it is true, It just replaces the progress bar with simple message.
Fix of Bug-2 : To fix this bug, PR increases the left_count by 1 because what was happening previously that if the plugin was running it assumed to be completed as it is was removed from work-list. Also at condition where left_count=1. PR checks the busy attribute of every worker and if no worker is running PR decreases the left_count by 1. Hence this fixes Bug-2
#644 
@delta24 @DePierre @DoomTaper @7a 
Tested on Firefox and Chrome, working on both the browsers
=> Progress Bar Bug Fixed. Fixes #644

framework/db/config_manager.py, framework/db/mapping_manager.py, framework/db/resource_manager.py
The config files will be checked for existence before reading it, to prevent exception.
issue #666 
@delta24 @DePierre 
Delete the config file in `profile` folder and try to run OWTF
=> Added file check before reading config files, Fixes #666

framework/db/plugin_manager.py
Added plugin name to code converter function so that before querying all plugin names are converted to their respective codes
#650 
@delta24 @DePierre 
tested command `./owtf.py -o Application_Discovery http://127.0.0.1`
=> Addded plugin name to code converter function Fixes #650

framework/interface/templates/target_manager.html
Added a js function which is called whenever the session model is closed.
* If a session is selected, no action is taken.
* If no session is selected
* If one one session is present, it is selected by default.
* Else a alert message is shown to select a session.
Issue #608 
@delta24
=> [ui] Added javascript function to check selected session, Fixes #608

framework/interface/templates/plugin_report.html
Plugin_types buttons added on panel bar to open it directly
As a part to decrease no. of clicks to quickly review all the plugins, new buttons added on panel bar so that clicked plugin_type can directly be opened from accordian. this will -1 the clicks.
@delta24 @7a @tunnelshade @anantshri
=> [webui] Plugin_types buttons added on panel bar to open it directly

gulpfile.js, webpack-dev.config.js
Production webpack config was taking huge time to create bundle because of compression because of that gulp was not working on sync with developer.
This PR will create webpack dev config which will be used by gulp that will build the bundle in about max  5 sec.
@delta24 @7a @tunnelshade @anantshri
=> [webui] Gulpfile bug fixed and webpack development config created

framework/db/target_manager.py, includes/css/stylesheet.css
As suggested by @7a , This PR globally apply colors for severity.
Colors are as follow:
"not ranked" = gray, "passing" = light green?, "info" = dark green?, "low" = blue, medium = yellow, high = red, critical = dark purple
@delta24 @7a
=> Global severity coloring

owtf.py
This will make owtf.py to build the bundle when owtf start.
@delta24 @7a
=> [webui] React bundle build at the start of owtf

install/distro-independent.cfg
Currently the link is broken and it returns 404.
This issue arises on installing OWTF. Currently the link is broken and it returns 404.
#745 
@delta24 @7a @anantshri
=> [install] CMS explorer download link changed.

framework/db/transaction_manager.py
Fixes the problem causing passive OWTF-IG-001 to stop.
The error occurs when this plugin is run against the target and later on deleted.
When this plugin is run again, as the target_id of the plugin has changed, causing the plugin to throw exception.
#750 
@delta24
Follow the following process:
* run `./owtf.py -o OWTF-IG-001 http://127.0.0.1`
* delete the target
* follow step 1 again
=> [misc] Fixed bug regarding OWTF-IG-001 passive plugin throwing exception

framework/lib/cli_options.py, owtf.py
It was not a good idea to build bundle on every startup of owtf.py Hence this PR will add functionality to provide --build-react flag to build bundle on startup.
@delta24 @7a 
…build bundle
=> [webui] Adds functionality to add --build-react flag to startup command

framework/interface/templates/base.html
Removes recently finished targets polling to improve performance
This is done because polling this endpoint is not much of importance and also it keeps server busy and hence decreases the performance.
@delta24 @7a
=> [webui] Removes recently finished targets polling to improve preformance

framework/db/poutput_manager.py, framework/interface/api_handlers.py, includes/src/Report/Accordians.js, includes/src/Report/Collapse.js, includes/src/Report/Header.js, includes/src/Report/Report.js, includes/src/Report/SideFilters.js, includes/src/Report/Table.js, includes/src/Report/Toolbar.js, package.json
This PR fixes many issues in new UI of report.
Changes:
* Previously, we make requests to server for every plugin. suppose if there are 136 plugins in report. Corresponding requests will be 136. This was hogging server due to large number of simultaneous requests. This PR eliminate that and sends the requests in parts of 30. So that there can max be 5 requests in case of 136. This eliminate hogging issue and also fasts the UI as we are doing the requests in parts.
* Previously, we make updated request(for data) for filtering to server anytime any filtering is requested. This PR eliminate server side filtering to client side filtering as we have all the data on load. So it is redundant to send the requests again. Now we just request the updated names of plugins after filtering which is …
=> Report fixes

install/distro-independent.cfg
Updated SSLLabs tool to newer version
#773 
@delta24 
Ran the newer version, fixed the issue
=> Updated ssllabs tool to remove the empty json error, Fixes #773

framework/plugin/worker_manager.py
Added the worker name in the dictionary used to send workers data.
The worker's log are written to the file named same as workers. The workers name is not sent in case of API call. This will add worker's name to the data sent.
#758 
Now the correct worker logs can be obtained using this data.
@delta24
=> Added a name field to the data sent about the workers, Fixes #758

framework/db/poutput_manager.py, framework/db/target_manager.py
Previously, Dashboard shows all items (not specific to active session)
This PR fixes this issue and will show results specific to active session.
Code wise change(For chart): Adds filter in DB queries for session.
For Panel: Get targets specific to session and filter plugin_outputs by targets too.
@delta24 @7a
=> [Dashboard] Adds multi session support to Dashboard

framework/db/target_manager.py, framework/interface/templates/target_manager.html
Previously, only 4 options were available 10,25,50,100. This fix will add another option to show all at once. 
Major concern of this fix is issue #821 . Logically, select all of target data-table is working correctly IMO it should only select visible entries. To fix #821 I think this should be a proper fix.
Advantage of this fix is suppose you want to carry out operation on particular set of 10 targets for say 20-30 targets you can go to pagination 2 and click select all. In this way this functionality gives you more options  and wider range of selection as compared to if you select **all** using **select all checkbox**.
@delta24 @7a
=> Adds support to show all targets

configuration/framework_config.cfg, framework/config/config.py, framework/db/plugin_manager.py
This bug was introduced in [this](https://github.com/owtf/owtf/commit/6c1ff855773914919f9c3dc3d213bdf0dce16ab4) commit.
If any configuration file is missing in `~/.owtf/` folder then current owtf expects it to be strictly in `@@@RootDir@@@/configuration/`. As the default plugin config files are in `@@@RootDir@@@/configuration/profiles/`, this makes default files unavailable.
The path of the config files should be stored in the framework config file and the function returning the path of config file must not have path hard coded.
This PR fixes the error in default path extraction. When default path is calculated it expects default file path relative to @@@RootDir@@@/configuration.
=> Fixed issue in path of plugin groups

framework/db/poutput_manager.py
Previously, if user ranks a plugins an api call only updates **user_rank** to corresponding rank.
Ideally we should also update owtf_rank because for suppose before rank PATCH call owtf ranks plugin to for say "info" but if we update the plugin user_rank to "passing" (because sometimes automated tools flag many things as findings which are really stupid) max_owtf_rank will still remain higher than max_user_rank for that target which is a bug actually. 
For example:
if only partially ranked, let's say, 3 automated plugins have an automated ranking and the human ONLY overwrote ONE, then **you still have to use the max of (automated, human) until the human overwrites the other automatically ranked plugins**.
Point is **if user_rank exist for some plugin then there is no requirement of …
=> Bug in ranking a plugin

install/arch/PKGBUILD, install/install.py, install/kali/install.sh, install/kali/kali_patch_w3af.sh, install/samurai/samurai_wtf_patch_w3af.sh
Some pip commands are not having --upgrade option, resulting in leaving dependencies in older version. This has created issues while installing OWTF (currently due to pyopenssl).
Added --upgrade option to all pip commands
#833
It will solve problem in installation of OWTF.
@viyatb
=> Added upgrade option to all pip commands, Fixes #833

install/install.py
Changes the virtualenv setup command to default to `python2.7` as the default version.
=> [virtualenv] Select python 2.7 as the default version for venv

framework/__init__.py, framework/utils.py, owtf.py
This PR forces OWTF to check if the Python virtualenv is activated before importing any OWTF modules in the main script.
=> [install] Move pre-launch checks to framework __init__.py file

Dockerfile, README.md
Fixes environment and interface issues with Docker Installations.
Previously, Interface was `127.0.0.1` due to which after binding the ports, tester couldn't access OWTF webUI.
This PR adds instructions to fix it.
@viyatb @7a 
Tested on docker container on mac OSX.
=> Adds environment and adds instructions for docker installation.

framework/interface/templates/base.html
Removes a css class "target-tab", the only <a> element in the menu with a class attribute, which causes the menu to render wrong in small screens as the screenshot shows. Also, clicking on the "target" menu did nothing (the link didn't work).
=> Fix responsive menu removing class in target menu which caused issues

framework/interface/reporter.py, includes/src/Report/Table.jsx
Fix issue when target url contains reserved characters (like questionmark)
There is an issue with the fileserver and the encoding when a target contains special characters. E.g: http://192.168.0.14/mutillidae/index.php?page=user-info.php
This tiny commit fixes it :)
=> Fix issue when target url contains reserved characters

includes/src/Transactions/TransactionTable.jsx
The proxy transactions should ideally be colored when "selected" => highlight the row.
#695 
@viyatb
=> [webui] Colors the proxy transactions when selected => highlight the row

framework/db/target_manager.py
Let `GetAll` function in `framework/db/poutput_manager.py` raise `InvalidTargetReference` if target not found.
@viyatb @DePierre @7a
=> Exception fix for GetAll function in framework/db/poutput_manager.py

framework/db/mapping_manager.py, framework/interface/api_handlers.py, framework/interface/urls.py, webui/src/Report/Accordian.jsx
Fixes the mapping filtering.
Fix adds mapping object with `/names` APIs which then used to filter mapping on client side only.
#695 
@viyatb @7a @DePierre
=> Fixes the Advance filter, mapping filter bug

owtf/webui/scss/main.scss, owtf/webui/src/main.js, owtf/webui/webpack.config.js, requirements.txt
Fix font-awesome not being loading after a fresh install issue.
Also upgrade PTP dependency to 0.4.2. Old PTP version caused errors with some plugins.
=> Tiny Fixes: Font-awesome not being loaded after a fresh install. PTP upgrade.

owtf/data/conf/general.cfg, owtf/install/install.cfg, owtf/install/install.py
1. Fix general.cfg tools pointing to old path. 
2. Fix ~/.owtf beeing overwritten every install.
3. Also, hoppy install path pointed to ~/.owtfs instead of ~/.owtf
=> Fix general.cfg and ~/.owtf beeing overwritten

owtf/data/conf/general.cfg, owtf/scripts/run_wapiti.sh
1. Changed Wapiti install directory
2. Updated run_wapiti.sh to include new version 3 requirements 
Wapiti is now installed in  /usr/local/bin/wapiti
-u [url] and it needs to include a forward slash...
Updates to allow Wapiti to function under Kali 2018.2
@viyatb 
Updated owtf-docker and added these small changes to it.
Installed and tested via 
`docker build -t owtf .`
`docker run -it -p 8008:8008 -p 8009:8009 -p 8010:8010 owtf /bin/bash`
=> Small updates to Wapiti

docker/Dockerfile
Outdated kali-linux-docker image replaced with the new kali-rollling image. Fixes the permission denied error while building the owtf docker image.
=> Dockerfile Fixed

owtf/api/handlers/work.py
`Delete All` button on the worklist page is working fine after the fix.
=> WorklistPage delete API fixed
